server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: 21471972
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: create


eureka.client.serviceUrl:
  defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: info

