server:
  port: 8080


spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/users
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

eureka.client.serviceUrl:
  defaultZone: http://eureka-server:8080/eureka