server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: 21471972
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update


eureka.client.serviceUrl:
  defaultZone: http://localhost:8761/eureka/


