server:
  port: 8080

spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: tasks
      port: 27017
      host: mongo
      auto-index-creation: true

eureka.client.serviceUrl:
  defaultZone: http://eureka-server:8080/eureka