server:
  port: 0

spring:
  application:
    name: task-manager
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: tasks
      port: 27017
      host: localhost
      auto-index-creation: true
  jpa:
    hibernate.ddl-auto: create-drop


eureka.client.serviceUrl:
  defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: info


