server:
  port: 0
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: task-manager
#  datasource:
#    url: jdbc:postgresql://localhost:5432/users
#    username: postgres
#    password: postgres
#    driverClassName: org.postgresql.Driver
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: tasks
      port: 27017
      host: localhost
  jpa:
    hibernate.ddl-auto: create


eureka.client.serviceUrl:
  defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: info


